environment:
  global:
    TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: stable
    PROJECT_NAME: json_typegen
    CARGO_HOME: "c:\\cargo"
    RUSTUP_HOME: "c:\\rustup"

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\cargo\bin
  - rustc -Vv
  - cargo -V

build: false

test_script:
  - cargo test --all --target %TARGET% --verbose

before_deploy:
  # Generate artifacts for release
  - cargo build --package json_typegen_cli --release --verbose
  - mkdir staging
  - copy target\release\json_typegen.exe staging
  - cd staging
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  description: 'Automatically deployed release'
  artifact: /.*\.zip/
  auth_token:
    secure: WkC84Y5M06+LO15MPsh4pN5X8cSIwwrifrJoINx3hfeMT/2c0ClCxooBnGga7V6g
  provider: GitHub
  on:
    appveyor_repo_tag: true

branches:
  only:
    - /^v\d+\.\d+\.\d+$/
    - master
